A1/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

wordbank/urls.py
from django.conf.urls import url

from . import views

app_name = 'wordbank'
urlpatterns = [
    url(r'^$', views.Home_page.as_view(), name='home_page'),
    ####################### latest 5 word######################
    url(r'^latest/$', views.latest_word.as_view(), name='latest_word'),
    ######################## all word #######################
    url(r'^all/$', views.AllView.as_view(), name='all_word'),
    url(r'^into_add_page/$', views.into_add_page, name='add_new_word'),
    url(r'^saveword/$', views.SaveWord, name='saveword'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='details'),
]

wordbank/models.py
from django.db import models

# Create your models here.
class word(models.Model):
    word_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.word_text


class details(models.Model):
    word = models.ForeignKey(word, on_delete=models.CASCADE)
    type_text = models.CharField(max_length=50)
    meaning_text = models.CharField(max_length=200)
    sentence_text = models.CharField(max_length=500)

wordbank/views.py
import csv
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone



from .models import word, details



class Home_page(generic.ListView):
    template_name = 'wordbank/home_page.html'
    context_object_name = 'latest_word_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return word.objects.order_by('-pub_date')[:5]
   
class latest_word(generic.ListView):
    template_name = 'wordbank/latest_word.html'
    context_object_name = 'latest_word_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return word.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = word
    template_name = 'wordbank/details.html'
    def get_queryset(self):
       return word.objects.filter(pub_date__lte=timezone.now())

class AllView(generic.ListView):
    template_name = 'wordbank/all_word.html'
    context_object_name = 'all_word_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return word.objects.order_by('word_text').all

def into_add_page(request):
    return render(request,'wordbank/add_new_word.html')

def SaveWord(request):

    if request.method == 'POST':
        add_word = request.POST['add_word']
        add_type = request.POST['add_type']
        add_mean = request.POST['add_mean']
        add_sentence = request.POST['add_sentence']
        add_datetime = timezone.now()

        new_word = word(
                word_text = add_word,
                pub_date  = add_datetime
                )
        new_word.save()

        new_details = details(
                word = new_word,
                type_text = add_type,
                meaning_text = add_mean,
                sentence_text = add_sentence
                )
        new_details.save()
    return HttpResponseRedirect(reverse('wordbank:home_page'))



       
       
       
        
            
          
 


    

wordbank/templates/wordbank/add_new_word.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
	</head>
		<body>
		<div class="header">
			<h1>Add New Word</h1>
		</div>
		<div class="nav">
			<a href="/" class="button"> back</a>	
		</div>
		<div class="section">
				<form action="{% url 'wordbank:saveword' %}" method="POST">
				{% csrf_token %}	
					Word      <span class="tab"><input type="text" name="add_word"><br/></span>
					Type      <span class="tab1"><input type="text" name="add_type" ><br/></span>
					Meannig   <span class="tab2"><input type="text" name="add_mean"  ><br/></span>
					Sentence  <span class="tab3"><input type="text" name="add_sentence"  ><br/></span>
					<span class="tab4"><input type="submit" name= "submit" value="submit" /></span>
					</form>
						
				</div>
		</body>
</html>

wordbank/templates/wordbank/all_word.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>show all word</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}" />
	</head>
		<body>
			<div class="header">
				<h1>All Word Bank</h1>	
			</div>
			<div class="nav">
				<a href="/ " class="button">Back</a>
			</div>
			<div class="section" >		
				{% if all_word_list %}
    				{% for word in all_word_list %}
        				<a href="{% url 'wordbank:details' word.id %}"> {{ word.word_text }}</a>
    				{% endfor %}
				{% else %}
	    			<p>No word are available.</p>
				{% endif %}
			</div>
		</body>
</html>
	
				
			

wordbank/templates/wordbank/details.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
	</head>
		
			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		<body>
			<div class="header">
				<h1>{{ word.word_text }}</h1>
			</div>
			<div class="nav">
				<a href="/ " class="button">Back</a>
			</div>
			
			<div class="section">
			
				{% for detials in word.details_set.all %}
					<table  cellpadding="5" cellspacing="100" width="500" height="20" >
						<tr>
							<td width="30%" bgcolor="#81BEF7" ><b> type :</b></td>
							<td bgcolor="#81BEF7" >  {{ detials.type_text }}</td>
						</tr>
						<tr>
    						<td width="30%" bgcolor="#FFFFFF"><b> meaning:</b></td>
    						<td bgcolor="#FFFFFF">{{ detials.meaning_text }}</td>
    					</tr>
    					<tr>
    						<td width="30%" bgcolor="#81BEF7"><b> sentence:</b></td> 
    						<td bgcolor="#81BEF7"> {{ detials.sentence_text }}</td>
    					</tr>
    				</table>
    				<hr>
				{% endfor %}
			</div>

		</body>
</html>

wordbank/templates/wordbank/home_page.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
	</head>
		<body>
			<div class="header">
				<h1>Word Bank</h1>
			</div>
			
				
			
			<div>
				<form action="{% url 'wordbank:latest_word'%}" method="post">
						{% csrf_token %}
						<br><br><br><br><br><br>
						<center>Search Word</center><br>
						<center><input type="text" name="term" size="30"> </center>
						<center><input type="submit" value="Search"></center>	
				</form>
			</div>
			<br><br><br>
				<center>
				<a  class="button1" href="{% url 'wordbank:all_word' %}">All Word</a>
				<a  class="button2"href="{% url 'wordbank:add_new_word' %}">Add Word</a>
				<a  class="button2"href="{% url 'wordbank:latest_word' %}">Latest Word</a>
				</center>
		</body>
</body>
<html>

wordbank/templates/wordbank/latest_word.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
	</head>
		<body>
			<div class="header">
				<h1>wordbank</h1>
			</div>
			<div class="nav">
				<h2><a href="/"  class="button" >back</a></h2>
			</div>
			<div class="section">
				{% if latest_word_list %}
    				{% for word in latest_word_list %}
       					<li><h2><a href="{% url 'wordbank:details' word.id %}">{{ word.word_text }}</a><h2></li> 
       				{% endfor %}
				{% else %}
    			<p>No word are available.</p>
				{% endif %}
			</div>
		</body>
</html>